-- ***********************************************************************************************
-- *** telescope  --highly extendable fuzzy finder over lists.
-- ***********************************************************************************************

return {
    -- "nvim-telescope/telescope.nvim",
    -- branch = "0.1.x",
    -- dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
    --     "nvim-tree/nvim-web-devicons",
    --     "folke/todo-comments.nvim",
    --     "nvim-telescope/telescope-ui-select.nvim",
    -- },
    -- config = function()
    --     local telescope = require("telescope")
    --     local actions = require("telescope.actions")
    --
    --     telescope.setup({
    --         defaults = {
    --             --    path_display = { "smart" },
    --             mappings = {
    --                 i = {
    --                     ["<C-k>"] = actions.move_selection_previous, -- move to prev result
    --                     ["<C-j>"] = actions.move_selection_next, -- move to next result
    --                     ["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
    --                 },
    --             },
    --         },
    --         extensions = {
    --             ["ui-select"] = {
    --                 require("telescope.themes").get_dropdown({
    --                     -- even more opts
    --                 }),
    --
    --                 -- pseudo code / specification for writing custom displays, like the one
    --                 -- for "codeactions"
    --                 -- specific_opts = {
    --                 --   [kind] = {
    --                 --     make_indexed = function(items) -> indexed_items, width,
    --                 --     make_displayer = function(widths) -> displayer
    --                 --     make_display = function(displayer) -> function(e)
    --                 --     make_ordinal = function(e) -> string
    --                 --   },
    --                 --   -- for example to disable the custom builtin "codeactions" display
    --                 --      do the following
    --                 --   codeactions = false,
    --                 -- }
    --             },
    --         },
    --     })
    --
    --     telescope.load_extension("fzf")
    --     telescope.load_extension("ui-select")
    --
    --     -- set keymaps
    --     local keymap = vim.keymap -- for conciseness
    --     local builtin = require("telescope.builtin")
    --
    --     keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Fuzzy find files in cwd" })
    --     keymap.set("n", "<leader>fo", "<cmd>Telescope oldfiles<cr>", { desc = "Fuzzy find recent files" })
    --     keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<cr>", { desc = "Find string in cwd" })
    --     keymap.set("n", "<leader>ft", "<cmd>TodoTelescope<cr>", { desc = "Find todo comments" })
    --     keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<cr>", { desc = "Navigate Current Open Buffers" })
    --     keymap.set("n", "<leader>fk", "<cmd>Telescope keymaps<cr>", { desc = "Search Telescope Keymaps" })
    --     keymap.set("n", "<leader>f?", function()
    --         vim.cmd(":h Telescope")
    --     end, { desc = "Telescope help documentation" })
    --
    --     keymap.set("n", "<leader>fs", function()
    --         builtin.grep_string({ search = vim.fn.input("Grep --> ") })
    --     end, { desc = "Find string under cursor in cwd" })
    --
    --     keymap.set("n", "<leader>fd", function() end, { desc = "Searches current file for functions" })
    -- end,
}
